name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-ios:
    type: build
    params:
      platform: ios
      profile: production
      working_directory: apps/mobile

  build-android:
    type: build
    params:
      platform: android
      profile: production
      working_directory: apps/mobile

